name: Flutter Web

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        #flutter-version: '1.12.x'
        channel: 'beta' # Currently you have to use beta channel for Flutter web.
    - run: flutter upgrade # You also get the flutter version
    - run: flutter config --enable-web
    - run: flutter packages get
    - run: flutter build web --release
    - run: pwd
    - run: ls
      working-directory: /home/runner/work/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/build/web
    
    # Bug https://github.com/flutter/flutter/issues/69287
    - run: cat index.html
      working-directory: /home/runner/work/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/build/web
    - run: sed -i '/base href/d' index.html #For MacOS : sed -i '' '/base href/d' index.html
      working-directory: /home/runner/work/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/build/web
    - run: cat index.html
      working-directory: /home/runner/work/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/build/web

    - run: git init
      working-directory: /home/runner/work/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/build/web
    - run: git config user.name  "CI"
      working-directory: /home/runner/work/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/build/web
    - run: git config user.email "flutter-ci@github.com"
      working-directory: /home/runner/work/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/build/web
    - run: git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/dleurs/Flutter-Navigator-2.0-demo-with-Authentication-mecanism.git
      working-directory: /home/runner/work/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/build/web
    - run: git checkout -b gh-pages
      working-directory: /home/runner/work/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/build/web
    - run: git add .
      working-directory: /home/runner/work/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/build/web
    - run: git commit -m "Updated docs" --allow-empty
      working-directory: /home/runner/work/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/build/web
    - run: git push --force secure-origin gh-pages
      working-directory: /home/runner/work/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/build/web